name: Sync and Deploy to Vercel

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [closed]
    branches: [main, develop]

jobs:
  sync-and-deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to forked repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_GITHUB_ACCESS_KEY }}
        with:
          source-directory: '.'
          destination-github-username: YOOJS1205
          destination-repository-name: photopic
          user-email: ${{ secrets.PERSONAL_EMAIL }}
          commit-message: ${{ github.event.commits[0].message || 'Sync from original repository' }}
          target-branch: ${{ github.ref_name }}
