name: Sync and Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  sync-and-deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.PERSONAL_EMAIL }}"
          git config --global user.name "GitHub Action"

      - name: Push to forked repository
        run: |
          git remote add fork https://${{ secrets.API_TOKEN_GITHUB }}@github.com/YOOJS1205/photopic.git
          git fetch fork
          git push -f fork ${GITHUB_REF#refs/heads/}:${GITHUB_REF#refs/heads/}
