name: Sync GitHub Issues to Notion

on:
  issues:
    types: [opened, closed, reopened]

jobs:
  sync-to-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sync to Notion
        uses: actions/github-script@v7
        env:
          NOTION_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        with:
          script: |
            const { Client } = require('@notionhq/client');
            const notion = new Client({ auth: process.env.NOTION_KEY });

            const issue = context.payload.issue;

            try {
              await notion.pages.create({
                parent: {
                  database_id: process.env.NOTION_DATABASE_ID,
                },
                properties: {
                  이름: {  // 기본 제목 필드
                    title: [
                      {
                        text: {
                          content: issue.title,
                        },
                      },
                    ],
                  },
                  상태: {  // 칸반보드의 상태
                    select: {
                      name: issue.state === 'open' ? '시작 전' : '완료',
                    },
                  },
                },
              });
              
              console.log(`Issue "${issue.title}" 가 Notion에 성공적으로 동기화되었습니다.`);
              
            } catch (error) {
              core.setFailed(`Notion 동기화 실패: ${error.message}`);
            }
