on:
  issues:
    types: [opened, reopened, closed, deleted]
jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Run github issue notion sync'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check files
        run: |
          pwd
          ls -la

      - name: create env file
        run: |
          touch .env
          echo PERSONAL_GITHUB_ACCESS_KEY=${{ secrets.PERSONAL_GITHUB_ACCESS_KEY }} >> .env
          echo NOTION_KEY=${{ secrets.NOTION_KEY }} >> .env
          echo NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }} >> .env
          echo REPO_OWNER=${{ github.repository_owner }} >> .env
          echo REPO_NAME=${{ github.event.repository.name }} >> .env

      - name: Run docker compose
        run: docker compose --env-file .env up
