name: Storybook Build Check

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build check
        run: yarn build-storybook --quiet

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-build
          path: storybook-static
