name: Sync and Deploy to Vercel

on:
  push:
    branches: [main, develop]

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.PERSONAL_EMAIL }}"
          git config --global user.name "GitHub Action"

      - name: Push to forked repository
        run: |
          echo "Setting up remote repository..."
          git remote add fork "https://oauth2:${{ secrets.API_TOKEN_GITHUB }}@github.com/YOOJS1205/photopic.git"
          echo "Fetching from fork..."
          git fetch fork
          echo "Current branch: ${GITHUB_REF#refs/heads/}"
          echo "Pushing to fork..."
          git push -f fork ${GITHUB_REF#refs/heads/}:${GITHUB_REF#refs/heads/}

      - name: Deploy to Vercel Production
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'

      - name: Deploy to Vercel Preview
        if: github.ref == 'refs/heads/develop'
        uses: amondnet/vercel-action@master
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
